annotations:
  charts.openshift.io/name: Openbao
apiVersion: v2
appVersion: v2.1.0
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://github.com/openbao/artwork/blob/main/color/openbao-color.svg
keywords:
- vault
- openbao
- security
- encryption
- secrets
- management
- automation
- infrastructure
kubeVersion: '>= 1.22.0-0'
maintainers:
- email: openbao-security@lists.lfedge.org
  name: OpenBao
  url: https://openbao.org
name: openbao
sources:
- https://github.com/openbao/openbao-helm
version: 0.7.0
